In [1]:
import pandas as pd

## Load The Dataset

In [3]:
sd = pd.read_csv('transactions.csv')

## See First 5 rows

In [4]:
sd .head()

,transaction_id,account_id,customer_id,timestamp,amount,currency,merchant_name,merchant_category,merchant_mcc,transaction_type,...,country,counterparty_iban,label,category,subcategory,is_subscription,is_salary,is_transfer,is_cash_withdrawal,balance_after_transaction
0,3609af85ea2f466f89d01ac1eb3431e9,A00000001,C0000001,2024-01-01T21:26:41,-1980.03,USD,Cardinal Regional Bank - Mortgage,finance,6012,ach_debit,...,US,NaN,LOAN PMT MORTGAGE,finance,mortgage,False,False,False,False,4953.46
1,27af5a3118b647e09e2ee206bc7b5f06,A00000001,C0000001,2024-01-01T09:22:32,-8.66,USD,Costco,groceries,5411,card_payment,...,US,NaN,COSTCO,groceries,supermarket,False,False,False,False,4944.80
2,e9a202dbdef54362b5563fa4522a3343,A00000001,C0000001,2024-01-01T18:45:24,-134.82,USD,Costco,groceries,5411,card_payment_contactless,...,US,NaN,COSTCO,groceries,supermarket,False,False,False,False,4809.98
3,860989e43f4a49b2be2ca5bab8d91009,A00000001,C0000001,2024-01-01T17:15:12,-158.25,USD,Best Buy,shopping,5722,card_payment_contactless,...,US,NaN,BEST BUY,shopping,electronics,False,False,False,False,4651.73
4,2bdd7dd39e934817a12161d4445fe430,A00000001,C0000001,2024-01-01T21:58:57,-60.01,USD,Local Diner,dining,5812,card_payment_contactless,...,US,NaN,LOCAL DINER,dining,restaurant,False,False,False,False,4591.72

## See Last 5 Rows

In [6]:
sd.tail()

,transaction_id,account_id,customer_id,timestamp,amount,currency,merchant_name,merchant_category,merchant_mcc,transaction_type,...,country,counterparty_iban,label,category,subcategory,is_subscription,is_salary,is_transfer,is_cash_withdrawal,balance_after_transaction
295,90fc088624724009a559fd9a7f4e8650,A00000005,C0000002,2024-01-28T22:16:47,-24.50,USD,Walmart,groceries,5411,card_payment_contactless,...,US,NaN,WALMART,groceries,supermarket,False,False,False,False,15450.72
296,c2a7448728ec45e3a2e3d1ed8d132dad,A00000005,C0000002,2024-01-28T13:27:03,-15.28,USD,DoorDash,dining,5812,card_payment_online,...,US,NaN,DOORDASH*,dining,delivery,False,False,False,False,15435.44
297,a7365b0b340844d5ad35b4f0acc2c369,A00000005,C0000002,2024-01-28T10:52:32,-54.40,USD,Uber Eats,dining,5812,card_payment_online,...,US,NaN,UBER EATS,dining,delivery,False,False,False,False,15381.04
298,744fa596f1a94b9a91a3ec7be62e84f9,A00000005,C0000002,2024-01-28T22:04:51,-171.80,USD,Macy's,shopping,5651,card_payment_contactless,...,US,NaN,MACY'S,shopping,clothing,False,False,False,False,15209.24
299,e414b49d8afb4345a3ebef3dbbc9552c,A00000005,C0000002,2024-01-29T17:16:04,-52.39,USD,Local Diner,dining,5812,card_payment_contactless,...,US,NaN,LOCAL DINER,dining,restaurant,False,False,False,False,15156.85

## Dataset Shape

In [7]:
sd.shape

(300, 22)

## Dataset Columns

In [10]:
print(sd.columns)

Index(['transaction_id', 'account_id', 'customer_id', 'timestamp', 'amount',
       'currency', 'merchant_name', 'merchant_category', 'merchant_mcc',
       'transaction_type', 'payment_channel', 'city', 'country',
       'counterparty_iban', 'label', 'category', 'subcategory',
       'is_subscription', 'is_salary', 'is_transfer', 'is_cash_withdrawal',
       'balance_after_transaction'],
      dtype='object')

## Dataset Info

In [8]:
sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   transaction_id             300 non-null    object
 1   account_id                 300 non-null    object
 2   customer_id                300 non-null    object
 3   timestamp                  300 non-null    object
 4   amount                     300 non-null    float64
 5   currency                   300 non-null    object
 6   merchant_name              300 non-null    object
 7   merchant_category          300 non-null    object
 8   merchant_mcc               300 non-null    int64
 9   transaction_type           300 non-null    object
 10  payment_channel            300 non-null    object
 11  city                       161 non-null    object
 12  country                    300 non-null    object
 13  counterparty_iban          2 non-null      object
 14  label                      300 non-null    object
 15  category                   300 non-null    object
 16  subcategory                300 non-null    object
 17  is_subscription            300 non-null    bool
 18  is_salary                  300 non-null    bool
 19  is_transfer                300 non-null    bool
 20  is_cash_withdrawal         300 non-null    bool
 21  balance_after_transaction  300 non-null    float64
dtypes: bool(4), float64(2), int64(1), object(15)
memory usage: 43.5+ KB

## Statistical Analysis

In [11]:
sd.describe()

            amount  merchant_mcc  balance_after_transaction
count   300.000000    300.000000                 300.000000
mean    -17.846400   5503.443333                4727.988867
std     865.737719   1036.999728                6176.908847
min   -2160.710000      0.000000               -1949.920000
25%     -94.922500   5411.000000                -603.437500
50%     -42.425000   5541.000000                2721.410000
75%     -18.000000   5814.000000               10164.845000
max    8837.870000   8021.000000               18020.210000

## Missing Value check and handle

In [12]:
sd.isnull().sum()

transaction_id                 0
account_id                     0
customer_id                    0
timestamp                      0
amount                         0
currency                       0
merchant_name                  0
merchant_category              0
merchant_mcc                   0
transaction_type               0
payment_channel                0
city                         139
country                        0
counterparty_iban            298
label                          0
category                       0
subcategory                    0
is_subscription                0
is_salary                      0
is_transfer                    0
is_cash_withdrawal             0
balance_after_transaction      0
dtype: int64

# Handle the nan